// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// Chunk represents a piece of information.
type Chunk struct {
	ID        string    `json:"id"`
	Kind      string    `json:"kind"`
	Data      string    `json:"data"`
	Tags      []string  `json:"tags"`
	AuthorID  string    `json:"author_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type CreateRequest struct {
	Kind string   `json:"kind"`
	Data string   `json:"data"`
	Tags []string `json:"tags"`
}

type ListFilter struct {
	Kind *string `json:"kind"`
}

type RegisterUserRequest struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type UpdateRequest struct {
	Tags []string `json:"tags"`
	Kind *string  `json:"kind"`
	Data *string  `json:"data"`
}

// User represents an entity that interacts with the system.
type User struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Chunks    []*Chunk  `json:"chunks"`
}
